export default {
  FETCH: 'FETCH',
  CANCEL_FETCH: 'CANCEL_FETCH',

  SET_OVERVIEW_DATA: 'SET_OVERVIEW_DATA',

  SET_MESSAGE: 'SET_MESSAGE', 
  CLEAR_MESSAGE: 'CLEAR_MESSAGE', 

  SET_GENRE_DATA: 'SET_GENRE_DATA',
  UPDATE_GENRE_DATA: 'UPDATE_GENRE_DATA',
  REMOVE_GENRE_DATA: 'REMOVE_GENRE_DATA',

  SET_ARTIST_DATA: 'SET_ARTIST_DATA',
  UPDATE_ARTIST_DATA: 'UPDATE_ARTIST_DATA',
  REMOVE_ARTIST_DATA: 'REMOVE_ARTIST_DATA',
};

